#!/usr/bin/env bash
set -euo pipefail

# Builds PDFs and generates a GitHub Pages-friendly site under ./docs
# (static HTML + PDFs). Intended to be repo-local (usable locally or in CI).

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

out_dir="docs"
mkdir -p "$out_dir"

# Compile everything (also refreshes cache via prepare_repo.sh)
./scripts/test_all.sh

# Copy root PDFs to docs/
shopt -s nullglob
pdfs=( *.pdf )

if [[ ${#pdfs[@]} -eq 0 ]]; then
  echo "build_pages: no PDFs produced" >&2
  exit 2
fi

# Clean old PDFs in docs, keep index.html
find "$out_dir" -maxdepth 1 -type f -name '*.pdf' -print0 | xargs -0 rm -f || true

for p in "${pdfs[@]}"; do
  cp -f "$p" "$out_dir/$p"
done

# Generate docs/index.html
index="$out_dir/index.html"
{
  echo "<!doctype html>"
  echo "<html lang=\"en\">"
  echo "<head>"
  echo "  <meta charset=\"utf-8\"/>"
  echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>"
  echo "  <title>momo-typst PDFs</title>"
  echo "  <style>body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;max-width:900px;margin:40px auto;padding:0 16px}h1{margin:0 0 12px}ul{padding-left:18px}li{margin:6px 0}code{background:#f2f2f2;padding:2px 4px;border-radius:4px}</style>"
  echo "</head>"
  echo "<body>"
  echo "  <h1>Compiled PDFs</h1>"
  echo "  <p>Generated by <code>./scripts/build_pages.sh</code>.</p>"
  echo "  <ul>"
  for p in "${pdfs[@]}"; do
    echo "    <li><a href=\"./$p\">$p</a></li>"
  done
  echo "  </ul>"
  echo "</body>"
  echo "</html>"
} > "$index"

echo "build_pages: wrote $index"
